#!/usr/bin/env zsh
#
#
STOW_FOLDERS='rofi,polybar,i3,nvim,picom,shell,tmux,variety,wezterm'
pushd ~/dotfiles
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done
popd
